//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-0fe630eb857a6ec83"
mykey = "your pem key"
tags = ["postgresql", "nodejs", "react"]
instancetype = "t2.micro"
controlinstancetype = "t3a.medium"
num = 3
region = "us-east-1"
mysecgr = "ansible-project-207-sec-gr"
user = "clarusway"